from web_browser_type import BrowserType


# Empty canvas - to show as a image copy and open as a link in web browser.
EMPTY_CANVAS = {BrowserType.CHROME:
                    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAADICAYAAAAQj4UaAAAMoElEQVR4Xu3XwQkAMAwDsXb/oV3oEPdSFjCIfO5u23EECBAgQIAAAQIECB"
                    "AIBK4ACZRNECBAgAABAgQIECDwBQSIRyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBASIHyBAgAABAgQIECBAIBMQIBm1IQIECBAgQIAAAQIEBIgfIECAAAECBAgQIEAgExAgGbUhAgQIECBAgAABAgQEiB8gQIAAAQIECB"
                    "AgQCATECAZtSECBAgQIECAAAECBB5FJB3Ww4px0gAAAABJRU5ErkJggg==",
                BrowserType.FIREFOX:
                    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAADICAYAAAAQj4UaAAAENElEQVR4nO3XMQEAMAyAsPo3vbpgRxMFvMwDAACIzO8AAADgDgMCAABkDA"
                    "gAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAAAAGQMCAABkDAgAAJAxIAAAQMaAAA"
                    "AAGQMCAABkDAgAAJBZL87N56EPU4wAAAAASUVORK5CYII="}


# 4410 is length of encoded empty canvas in Chrome
# 1534 is length of encoded empty canvas in Chrome
EMPTY_CANVAS_LENGTH = {BrowserType.CHROME: len(EMPTY_CANVAS[BrowserType.CHROME]),
                       BrowserType.FIREFOX: len(EMPTY_CANVAS[BrowserType.FIREFOX])}
